homepage:
    pattern:  /
    defaults: { _controller: FilmsCatalogBundle:Default:index }

film_view:
    pattern:  /film/view/{id}
    defaults: { _controller: FilmsCatalogBundle:Film:index }

film_delete:
    pattern:  /film/delete/{id}
    defaults: { _controller: FilmsCatalogBundle:Film:remove }

film_create:
    pattern:  /film/create
    defaults: { _controller: FilmsCatalogBundle:Film:create }

film_creator:
    pattern:  /film/creator
    defaults: { _controller: FilmsCatalogBundle:Film:add }
    methods:  [POST]

category_view:
    pattern:  /category/{slug}
    defaults: { _controller: FilmsCatalogBundle:Category:index }

category_delete:
    pattern:  /category/delete/{id}
    defaults: { _controller: FilmsCatalogBundle:Category:remove }

