homepage:
    pattern:  /
    defaults: { _controller: FilmsCatalogBundle:Default:index }

film_view:
    pattern:  /film/view/{id}
    defaults: { _controller: FilmsCatalogBundle:Film:index }

film_delete:
    pattern:  /film/delete/{id}
    defaults: { _controller: FilmsCatalogBundle:Film:remove }

category_view:
    pattern:  /category/{id}
    defaults: { _controller: FilmsCatalogBundle:Category:index }

category_delete:
    pattern:  /category/delete/{id}
    defaults: { _controller: FilmsCatalogBundle:Category:remove }

